#!/bin/sh

set -e

systemctl --no-reload disable --now ${pkg.name}.service > /dev/null 2>&1 || :

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi

exit 0
