#!/bin/sh

set -e

abort_install() {
	echo "${1}"
	exit 1
}

eula="$(cat <<'EOF'
${pkgEula}
EOF
)"

whiptail --scrolltext --title "ThingsBoard Professional Edition License Agreement" --msgbox "${eula}" 20 78

if ! (whiptail --title "ThingsBoard Professional Edition License Agreement" --yesno "Do you accept the license agreement?" 8 78); then
    abort_install "The installation have been aborted because you do not agree with the license terms of this software."
fi

getent group ${pkg.user} >/dev/null || groupadd -r ${pkg.user}
getent passwd ${pkg.user} >/dev/null || \
useradd -d ${pkg.installFolder} -g ${pkg.user} -M -r ${pkg.user} -s /sbin/nologin \
-c "Thingsboard application"
