/**
 * Copyright © 2016-2026 The Thingsboard Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
syntax = "proto3";

option go_package = "github.com/thingsboard/tb-agent/gen/agent/v1;agentv1";

option java_package = "org.thingsboard.server.gen.agent.v1";
option java_multiple_files = true;

option java_outer_classname = "AgentProtos";

service AgentRpcService {
  rpc controlStream(stream AgentToServer) returns (stream ServerToAgent);
}

message AgentToServer {
  oneof msg {
    Hello hello = 1;
    CommandAck commandAck = 2;
    CommandProgress progress = 3;
    CommandResult result = 4;
    ComposeStateSync composeSync = 5;
  }
}

message ComposeStateSync {
  ConfigType configType = 1;
  string projectName = 2;
  string composeJson = 3;
}

message ServerToAgent {
  oneof msg {
    HelloAck helloAck = 1;
    AppCommand appCommand = 2;
  }
}

message AppCommand {
  CommandId commandId = 1;
  AppCommandAction action = 2;
  StepId stepId = 3;
  string appName = 4;
  ConfigType configType = 5;
  map<string, string> metadata = 6;
  int32 totalSteps = 7;
}

enum AppCommandAction {
  APP_INSTALL = 0;
  APP_UPDATE = 1;
  APP_DELETE = 2;
  APP_RESTART = 3;
  APP_ROLLBACK = 4;
  APP_UPGRADE = 5;
}

enum ConfigType {
  DOCKER_COMPOSE = 0;
}

message Hello {
  string routingKey = 1;
  string routingSecret = 2;
}

message HelloAck {
  bool success = 1;
}

message CommandAck {
  CommandId commandId = 1;
  AckStatus status = 2;
  optional string message = 3;
}

enum AckStatus {
  ACCEPTED = 0;
  REJECTED = 1;
}

message CommandProgress {
  CommandId commandId = 1;
  optional string stage = 2;
  optional string message = 3;
  StepId step = 4;
}

message CommandResult {
  CommandId commandId = 1;
  bool success = 2;
  optional string message = 3;
  StepId step = 4;
}

message StepId {
  int64 idMSB = 1;
  int64 idLSB = 2;
}

message CommandId {
  int64 idMSB = 1;
  int64 idLSB = 2;
}
